// Copyright © 2018 TermySequence LLC
//
// SPDX-License-Identifier: GPL-2.0-only

#pragma once

#define PALETTE_SIZE                300
#define PALETTE_STANDARD_MASK       255
#define PALETTE_APP                 256
#define PALETTE_APP_SIZE            44

#define PALETTE_COLOR               0x0ffffff
#define PALETTE_DISABLED            0x1000000
#define PALETTE_VALUEMASK           0x1ffffff
#define PALETTE_IS_ENABLED(x)       (((x) & PALETTE_DISABLED) == 0)
#define PALETTE_IS_DISABLED(x)      (((x) & PALETTE_DISABLED) != 0)

#define PALETTE_APP_FG              (PALETTE_APP + 4)
#define PALETTE_APP_BG              (PALETTE_APP + 5)
#define PALETTE_APP_HANDLE_OFF      (PALETTE_APP + 14)
#define PALETTE_APP_HANDLE_ON       (PALETTE_APP + 15)

#define PALETTE_SH_NOTE_BG          (PALETTE_APP + 16)
#define PALETTE_SH_NOTE_FG          (PALETTE_APP + 17)
#define PALETTE_SH_MATCHTEXT_BG     (PALETTE_APP + 18)
#define PALETTE_SH_MATCHTEXT_FG     (PALETTE_APP + 19)
#define PALETTE_SH_MATCHLINE_BG     (PALETTE_APP + 20)
#define PALETTE_SH_MATCHLINE_FG     (PALETTE_APP + 21)
#define PALETTE_SH_SELECTED_BG      (PALETTE_APP + 22)
#define PALETTE_SH_SELECTED_FG      (PALETTE_APP + 23)
#define PALETTE_SH_PROMPT_BG        (PALETTE_APP + 24)
#define PALETTE_SH_PROMPT_FG        (PALETTE_APP + 25)
#define PALETTE_SH_COMMAND_BG       (PALETTE_APP + 26)
#define PALETTE_SH_COMMAND_FG       (PALETTE_APP + 27)
#define PALETTE_SH_MARK_SELECTED_BG (PALETTE_APP + 28)
#define PALETTE_SH_MARK_SELECTED_FG (PALETTE_APP + 29)
#define PALETTE_SH_MARK_PROMPT_BG   (PALETTE_APP + 30)
#define PALETTE_SH_MARK_PROMPT_FG   (PALETTE_APP + 31)
#define PALETTE_SH_MARK_RUNNING_BG  (PALETTE_APP + 32)
#define PALETTE_SH_MARK_RUNNING_FG  (PALETTE_APP + 33)
#define PALETTE_SH_MARK_EXIT0_BG    (PALETTE_APP + 34)
#define PALETTE_SH_MARK_EXIT0_FG    (PALETTE_APP + 35)
#define PALETTE_SH_MARK_EXITN_BG    (PALETTE_APP + 36)
#define PALETTE_SH_MARK_EXITN_FG    (PALETTE_APP + 37)
#define PALETTE_SH_MARK_SIGNAL_BG   (PALETTE_APP + 38)
#define PALETTE_SH_MARK_SIGNAL_FG   (PALETTE_APP + 39)
#define PALETTE_SH_MARK_NOTE_BG     (PALETTE_APP + 40)
#define PALETTE_SH_MARK_NOTE_FG     (PALETTE_APP + 41)
#define PALETTE_SH_MARK_MATCH_BG    (PALETTE_APP + 42)
#define PALETTE_SH_MARK_MATCH_FG    (PALETTE_APP + 43)
